main : CLProcessPipeQueueTester.o 
	g++ -o main CLProcessPipeQueueTester.o  -L../../ -lexecutive -g -lpthread


CLProcessPipeQueueTester.o : CLProcessPipeQueueTester.cpp
	g++ -o CLProcessPipeQueueTester.o -c CLProcessPipeQueueTester.cpp -L../../ -lexecutive -I../../include -g




