#!/bin/bash
rm logger
cd test_for_exec
cd test_for_CLConditionVariable
rm logger
cd ..
cd test_for_CLEvent_Auto
rm logger
cd ..
cd test_for_CLEvent_Semaphore
rm logger
cd ..
cd test_for_CLMutex_RecordingLock
rm logger
cd ..
cd test_for_CLMutex_RecordingLockAndPThread
rm logger
cd ..
cd test_for_CLMutex_SharePThread
rm logger
cd ..
cd test_for_CLNonThreadForMsgLoop_Stress_Testing
rm logger
cd ..
cd test_for_CLProcess
rm logger
cd ..
cd test_for_CLSharedConditionVariableAllocator
rm logger
cd ..
cd test_for_CLSharedMemory
rm logger
cd ..
cd test_for_CLSharedMutexAllocator
rm logger
cd ../..
cd test
rm logger
