main : CLSelfPostPrivatePipeQueueTester.o 
	g++ -o main CLSelfPostPrivatePipeQueueTester.o  -L../../ -lexecutive -g -lpthread


CLSelfPostPrivatePipeQueueTester.o : CLSelfPostPrivatePipeQueueTester.cpp
	g++ -o CLSelfPostPrivatePipeQueueTester.o -c CLSelfPostPrivatePipeQueueTester.cpp -L../../ -lexecutive -I../../include -g

