main : CLProcessTestProvider.o 
	g++ -o main CLProcessTestProvider.o  -L../../ -lexecutive -g -lpthread


CLProcessTestProvider.o : CLProcessTestProvider.cpp
	g++ -o CLProcessTestProvider.o -c CLProcessTestProvider.cpp -L../../ -lexecutive -I../../include -g




