#ifndef ErrorCode_H
#define ErrorCode_H

const int NORMAL_ERROR = 0;

const int RECEIVED_ZERO_BYTE = 10;
const int RECEIVED_ERROR = 11;
const int RECEIVED_PENDING = 12;

const int MSG_RECEIVED_ZERO = RECEIVED_ZERO_BYTE;
const int MSG_RECEIVED_ERROR = RECEIVED_ERROR;
const int MSG_RECEIVED_PENDING = RECEIVED_PENDING;

const int IOVECTOR_ITERATOR_END = 20;

const int DATA_POSTER_INITIALIZE_SUCCESS = 30;
const int DATA_POSTER_INITIALIZE_PENDING = 31;
const int DATA_POSTER_INITIALIZE_ERROR = 32;

const int DATA_POSTER_POST_SUCCESS = 40;
const int DATA_POSTER_POST_PENDING = 41;
const int DATA_POSTER_POST_PARTIAL = 42;
const int DATA_POSTER_POST_ERROR = 43;

const int MSG_INITIALIZE_SUCCESS = DATA_POSTER_INITIALIZE_SUCCESS;
const int MSG_INITIALIZE_PENDING = DATA_POSTER_INITIALIZE_PENDING;
const int MSG_INITIALIZE_ERROR = DATA_POSTER_INITIALIZE_ERROR;

const int MSG_POST_SUCCESS = DATA_POSTER_POST_SUCCESS;
const int MSG_POST_PARTIAL = DATA_POSTER_POST_PARTIAL;
const int MSG_POST_PENDING = DATA_POSTER_POST_PENDING;
const int MSG_POST_ERROR = DATA_POSTER_POST_ERROR;

#endif