#ifndef ErrorCode_H
#define ErrorCode_H

const int NORMAL_ERROR = 0;

const int RECEIVED_ZERO_BYTE = 10;
const int RECEIVED_ERROR = 11;
const int RECEIVED_PENDING = 12;

const int MSG_RECEIVED_ZERO = RECEIVED_ZERO_BYTE;
const int MSG_RECEIVED_ERROR = RECEIVED_ERROR;
const int MSG_RECEIVED_PENDING = RECEIVED_PENDING;

const int IOVECTOR_ITERATOR_END = 10;

const int DATA_POSTER_INITIALIZE_SUCCESS = 0;
const int DATA_POSTER_INITIALIZE_PENDING = 1;
const int DATA_POSTER_INITIALIZE_ERROR = 2;

const int DATA_POSTER_POST_SUCCESS = 0;
const int DATA_POSTER_POST_PENDING = 1;
const int DATA_POSTER_POST_PARTIAL = 3;
const int DATA_POSTER_POST_ERROR = 2;

const int MSG_POST_INIT_SUCCESS = 0;
const int MSG_POST_INIT_FAILURE = 2;

const int MSG_POST_SUCCESS = 0;
const int MSG_POST_PARTIAL = 1;
const int MSG_POST_FAILURE = 2;

#endif