main : CLSharedPipeQueueTester.o 
	g++ -o main CLSharedPipeQueueTester.o  -L../../ -lexecutive -g -lpthread


CLSharedPipeQueueTester.o : CLSharedPipeQueueTester.cpp
	g++ -o CLSharedPipeQueueTester.o -c CLSharedPipeQueueTester.cpp -L../../ -lexecutive -I../../include -g




